# 请根据自身需求修改
APP_TITLE: xApp-test
APP_SUMMARY: xxApp-test
APP_DESCRIPTION: xxxApp-test
APP_VERSION: 1.0.0
APP_DEBUG: true
APP_LOG_SERIALIZE: false
APP_LOG_OUTDIR: ./logs
APP_DISABLE_DOCS: false
APP_ALLOW_CREDENTIALS: true
APP_ALLOW_ORIGINS:
  - "*"
APP_ALLOW_METHODS:
  - "*"
APP_ALLOW_HEADERS:
  - "*"
# #
DB_DRIVERNAME: sqlite
DB_ASYNC_DRIVERNAME: sqlite+aiosqlite
DB_DATABASE: app_test.sqlite3
DB_USERNAME:
DB_PASSWORD:
DB_HOST:
DB_PORT:
DB_CHARSET:
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_DB: 0
REDIS_PASSWORD:
REDIS_MAX_CONNECTIONS:
# #
CELERY_BROKER_URL: redis://:<password>@<host>:<port>/<db>
CELERY_BACKEND_URL: redis://:<password>@<host>:<port>/<db>
CELERY_TIMEZONE: Asia/Shanghai
CELERY_ENABLE_UTC: true
CELERY_TASK_SERIALIZER: json
CELERY_RESULT_SERIALIZER: json
CELERY_ACCEPT_CONTENT: [json]
CELERY_TASK_IGNORE_RESULT: false
CELERY_RESULT_EXPIRE: 86400
CELERY_TASK_TRACK_STARTED: true
CELERY_WORKER_CONCURRENCY: 8
CELERY_WORKER_PREFETCH_MULTIPLIER: 2
CELERY_WORKER_MAX_TASKS_PER_CHILD: 100
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: true
CELERY_TASK_REJECT_ON_WORKER_LOST: true
